version: '3.8'

services:
    localstack:
        container_name: 'localstack-todo'
        image: localstack/localstack
        environment:
            - SERVICES=lambda,apigateway,dynamodb
            - AWS_DEFAULT_REGION=us-east-1
            - DEBUG=1
        ports:
            - '4566:4566'            
        volumes:
            - '${TMPDIR:-/tmp/localstack}:/var/lib/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'
